#include <Arduino.h>
#include "sensors.hpp"

Ultrasonic front_left_ultrasonic(forward_left_ultrasonic_trig_pin, forward_left_ultrasonic_echo_pin);
Ultrasonic front_right_ultrasonic(forward_right_ultrasonic_trig_pin, forward_right_ultrasonic_echo_pin);
Ultrasonic left_ultrasonic(left_ultrasonic_trig_pin, left_ultrasonic_echo_pin);
Ultrasonic right_ultrasonic(right_ultrasonic_trig_pin, right_ultrasonic_echo_pin);


Illumination_sensor front_left_illumination_sensor{ forward_left_illumination_pin };
Illumination_sensor front_right_illumination_sensor{ forward_right_illumination_pin };
Illumination_sensor back_illumination_sensor{ backward_illumination_pin };

Infrared_sensor infrared;